### ISSUE TITLE
使用GitHub Actions任务更新源仓库代码。

### ISSUE THREAD

**Issue by JunzhouLiu** [JunzhouLiu/BILIBILI-HELPER#8]
该方案来自 @happy888888  #6 ，由于本操作会覆盖用户自己的`config.json`配置文件，所以暂时没有合并到`main`分支，所以请使用自定义功能的朋友请慎用。

在`./github/workflows`目录下创建`auto_merge.yml`文件，内容如下

```yml
name: auto_merge

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * fri


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Load upstream commits
      run: |
        git update-index --assume-unchanged ./src/main/resources/config.json
        git pull https://github.com/JunzhouLiu/BILIBILI-HELPER.git --log --no-commit
    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: main
      run: git push origin $DOWNSTREAM_BRANCH
```
